### ISSUE TITLE
Create a sample browser test

### ISSUE THREAD

**Issue by will-byrne** [libero/reviewer-client#34]
Create a sample browser test that tests the login page using the chosen library

**Comment by giorgiosironi** [comment]
Interested; if we had a Github team like @libero/infrastructure-reviewers but oriented to testing, would it help to share good ideas and patterns?

**Comment by erezmus** [comment]
aren't we all tester?

**Comment by giorgiosironi** [comment]
Loosely everyone is a T-shaped person with specializations and broader knowledge, but some people go deeper into the T leg when it comes to testing strategy and as an interest.

**Comment by erezmus** [comment]
where @will-byrne is the defacto test guy in reviewer.
