### ISSUE TITLE
Investigate amount of work to de-journalise 

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-client#46]
As part of the work for #43 to get login to work for the demo - the routing is fixed for use with eLife.

Investigate how much work it would take to make this configurable - so libero has the ability to insert routes such as this for login. 

Initial research seemed to suggest there are patterns you can follow to do this, such as: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config

If this is not a big job ~1 day then feel free to implement - just don't commit before the demo on 29th November 2019 :grin:

**Comment by erezmus** [comment]
The redirect we implemented is quite particular to using journal for logging in. It depends on how often this situation would occur with providers

**Comment by erezmus** [comment]
Identified 3 scenarios

### No token exchange
1. User Agent (UA) is directed to external Login service (`client_login_url`)
1. UA is redirected to `client_logged_in_url` with new token
1. UA stores token in local storage

### Token exchange
1. User Agent (UA) is directed to external Login service (`client_login_url`)
1. Login service returns token to UA on token exchange url (`client_token_exchange_url`)
1. UA requests token exchange to Token Exchange service (e.g. `continuum-auth`) which is proxied (`token_exchange_proxy_url`)
1. UA is redirected to `client_logged_in_url` with new token
1. UA stores token in local storage

### Token exchange, Journal (Currently on staging)
1. User Agent (UA) is directed to external Login service (`login_url`)
1. Login service returns token to UA on token fix url (`client_hash_token_redirect_url`), which converts the passed token from url hash component to path component for the token exchange url (`client_token_exchange_url`)
1. UA requests token exchange to Token Exchange service (e.g. `continuum-auth`) which is proxied to(`token_exchange_proxy_url`)
1. UA is redirected to `client_logged_in_url` with new token
1. UA stores token in local storage


From this we can infer that:
* Client App should have the following 4 configuration settings:
  * `client_login_url`: where the user is directed when attempting login.
  * `client_logged_in_url`: final step of login process where token is stored in local storage
  * `client_token_exchange_url`: url used for doing a token exchange
  * `client_hash_token_redirect_url`: url used for fixing url with token in hash (#) component from Login service (e.g. Journal)
* The Client Proxy (webpack dev server or nginx), should have the following settings:
  * `token_exchange_proxy_url`:  where to proxy requests for exchanging token to
  * `client_logged_in_url`: where to redirect UA after token exchange
* The Login service (e.g. Journal) should have the following settings:
  * A return url which can be set to the same value as either
    * `client_login_url` (No Token exchange)
    * `client_token_exchange_url` (Token exchange)
    * `client_hash_token_redirect_url` (Token exchange, Journal)
  * A secret for signing JWT token
* The token exchange service (e.g. continuum-auth), needs the following settings
  * Secret for verifying incoming token (same as the Login service one)
  * Secret for signing new token (Libero specific)

The next step is figuring out how to setup configuration to encompass those 3 scenarios

**Comment by diversemix** [comment]
Names have changed but the stories the same :laughing: 

![2019-12-02 15 20 19](https://user-images.githubusercontent.com/8524685/70036494-cad90580-15ac-11ea-88b5-6be2c8511fe5.jpg)

**Comment by erezmus** [comment]
case closed
