### ISSUE TITLE
Create browser tests for shoot-off 

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-client#49]
- [x] Create browser tests for shoot-off for Nightwatch
- [x] Create browser tests for shoot-off for TestCafe

**Comment by will-byrne** [comment]
Completed and the times are as follows:
```
Nightwatch
1)   12.3, 12.52, 12.61
5)   29.61, 29.11, 29.5
10)  51.37, 52.17, 51.15
20)  91.23, 93.46, 94.53
50)  215.36, 215.61, 215.74
100) 346.2, 370.38, 390.28

Testcafe
1)   24.7, 25.61, 26.16
5)   72.38, 49.02, 69.09
10)  124.66, 125.69, 124.51
20)  234.37, 234.32, 234.46
50)  565.87, 570.01, 567.62
100) 1125.78, 1126.74
```
ten tests per file with a simple form with two text fields, a text area, a drop down box and a button which navigates to another page.
![image (1)](https://user-images.githubusercontent.com/13573277/70238645-90649980-1761-11ea-901f-6b34403b4b40.png)
