### ISSUE TITLE
Investigate: Using browserstack for acceptance tests 

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-client#64]
We should be running PR browser tests in the pipeline against a single fixed version of a browser ie: chrome vX.X.X then running master merge pipeline over a number of different browsers using browserstack. This should allow us to maintain a quick pipeline for PRs whilst also letting us block deployment of any changes which break in other browsers.

**Comment by giorgiosironi** [comment]
I assume the main problem to solve here is that you need an environment accessible from the public Internet to deploy the application for those browsers to see it; or, some tunneling where they can see your localhost.
