### ISSUE TITLE
Discovery for Form library/framework

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-client#81]
Take some time to think (due diligence) on where we are going with the form building - 

see - https://json-schema.org/implementations.html#web-ui-generation

**Comment by Cooryd** [comment]
Some options for form state/ validation management 

- https://react-hook-form.com/
- https://jaredpalmer.com/formik
- https://github.com/Rocketseat/unform

**Comment by norisalsaadie** [comment]
Also adding this into the mix

- https://react-hook-form.com/

**Comment by Cooryd** [comment]
Check list of framework requirements:

- [ ] typescript support
- [ ] re-render performance (especially for nested field sets)
- [ ] built in validation 
- [ ] nested data handling
- [ ] accessibility

**Comment by Cooryd** [comment]
ADR to be produced based on #83 #84
