### ISSUE TITLE
Investigate Formik library for Submission Wizard

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-client#83]
Create a demo form application using `Formik` to evaluate of the following areas: 

- [x] typescript support - very good
- [x] re-render performance (especially for nested field sets) - improving, but not terrible.
- [x] built in validation - Default uses Yup, but manual validation is possible
- [x] nested data handling - based naming convention. Which is reasonable
- [x] accessibility

Findings should be added to an ADR document.

**Comment by norisalsaadie** [comment]
repo - https://github.com/erezmus/formik-vs-hooks - check relevant branch

**Comment by norisalsaadie** [comment]
Recent perf issues were addressed as outlined here and related issues https://github.com/jaredpalmer/formik/issues/1974

**Comment by norisalsaadie** [comment]
Accessibility guidelines outlined here https://dev.to/ptrin/accessible-formik-forms-2gld found via https://jaredpalmer.com/formik/docs/resources#community-articles-tutorials
