### ISSUE TITLE
Investigate React Hook Form for use in submission wizard

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-client#84]
https://react-hook-form.com/

Create a demo form application using `react-hook-form` to evaluate of the following areas: 

- [x] typescript support - written in typescript so complete TS support however when using ie11 import there is some additional TS config needed (see below) .
- [x] re-render performance (especially for nested field sets)
- [x] built in validation - `yup` and manual validation available.
- [x] nested data handling - specific util for registering field arrays and parsing of field names to form data nested properties  ( 'address.town' to `{address: {town: ''}`)
- [x] accessibility 

Findings should be added to an ADR document.

**Comment by Cooryd** [comment]
Doesn't natively support IE11, would need polyfill https://react-hook-form.com/faqs#BrowserSupport

**Comment by Cooryd** [comment]
Something we will probably need to account for https://github.com/react-hook-form/react-hook-form/issues/859#issuecomment-575839016

**Comment by Cooryd** [comment]
If using the IE11 import we'd need to declare the following to get typescript support working again:

`declare module "react-hook-form/dist/react-hook-form.ie11" {
  export * from "react-hook-form";
}`

**Comment by Cooryd** [comment]
Pros: 

- uncontrolled so keystrokes don't trigger re-renders. This gives huge performance boosts for large field-set pages (not that we currently have any).
- Lightweight 6kb lib size which is smaller than others also comes with no sub-dependancies 
- Concise easy to read code, hook based and most logic ends up in `ref` or initial hook call. No wrapping component or HOC required.
- Fast community response time. Only 1 open issue at the moment with maintainer response on 60+ contributors + numerous backers
- Lots of existing performance comparison out there so can base decision on that + our own investigation (https://github.com/react-hook-form/performance-compare)

Cons:
- IE11 oddities (still is supported through targeted package artefact. May require some polyfills)
- Relatively new(<12months since first tagged release) 
- Limited developer experience with lib

Things to note:
- documentation seems good for basic usage. Some of the FAQ things around testing ect. have slightly confusing wording.
- little out there of example wizard + auto-save when using the library. The lib shouldn't concern itself on how this is achieved though so not a con.

**Comment by norisalsaadie** [comment]
repo - https://github.com/erezmus/formik-vs-hooks - check relevant branch

**Comment by norisalsaadie** [comment]
Accessiblity guidelines outlined here https://dev.to/ptrin/accessible-formik-forms-2gld found via https://jaredpalmer.com/formik/docs/resources#community-articles-tutorials
