### ISSUE TITLE
Start Submission buttons should take user to the article type view 

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-client#88]
Clicking blue buttons should no longer create a new submission so we need to remove use of mutation here. Depending on the decision made in #87 clicking the blue start submission buttons on the No Submissions screen or the dashboard screen the app should either navigate to the right page or open an overlay. Unit tests should be amended for this too.

**Comment by erezmus** [comment]
currently exploring this as part of #87, so hold off picking this up for now
