### ISSUE TITLE
Add loading state to button

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-client#98]
For button clicks in the application that cause an asynchronous action (ie: graphql mutations) it would be useful to feed back to the user that something is happening. This should probably be in the form of a button loading state which could be something like a spinner replacing the buttons text while it's in that state. @chugginselifesciences will confirm design details on how this should appear.

Once implemented we should update ArticleType view to use loading state when a submission is in the process of being started and the user is waiting to be directed to the wizard form.

**Comment by chugginselifesciences** [comment]
@Cooryd I realised this is something we already do on journal when loading listings.

I can't find anything in Pattern Lab to share or help you find code to replicate, so I suggest checking in with @davidcmoulton or @discodavey to see if they can help you find something you can re-use. I'd be happy to investigate with them and then put something together in Sketch & InVision but I'm assuming it's easier to go to them direct?

![image](https://user-images.githubusercontent.com/41907215/73755296-ba383d80-475d-11ea-8a99-f876cfa8645c.png)

**Comment by discodavey** [comment]
There is no loading button in the pattern library that I am aware of as I have just searched for one. Perhaps @davidcmoulton knows of one that is labelled with a different name?
